CREATE TABLE IF NOT EXISTS app_write_lock (id TINYINT PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO app_write_lock VALUES (1);
ALTER TABLE comodatos ADD COLUMN IF NOT EXISTS devolvido_em DATETIME NULL;
