<?php
$total=(int)query('SELECT COUNT(*) FROM inventario WHERE ativo=1')->fetchColumn();
$used=(int)query('SELECT COUNT(DISTINCT inventario_id) FROM comodato_itens WHERE ativo=1')->fetchColumn();
$open=(int)query('SELECT COUNT(*) FROM comodatos WHERE ativo=1')->fetchColumn();
$late=(int)query('SELECT COUNT(*) FROM comodatos WHERE ativo=1 AND data_fim<CURDATE()')->fetchColumn();
$cards=[['Itens disponíveis',max(0,$total-$used),'Prontos para um novo empréstimo','inventario&status=available'],['Itens em comodato',$used,'Equipamentos com colaboradores','inventario&status=loaned'],['Comodatos abertos',$open,'Contratos em acompanhamento','comodatos&status=1'],['Devoluções em atraso',$late,'Previsão de devolução vencida','comodatos&status=overdue']];
?>
<div class="metrics"><?php foreach($cards as $i=>$c): ?><a class="metric metric-<?= $i ?>" href="app.php?module=<?= $c[3] ?>"><span><?= $c[0] ?></span><strong><?= $c[1] ?></strong><small><?= $c[2] ?> ↗</small></a><?php endforeach ?></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Próximas devoluções</h2><p>Priorize os equipamentos que precisam de acompanhamento.</p></div><a href="app.php?module=comodatos&status=1">Ver todos →</a></div><div class="table-wrap"><table><thead><tr><th>Comodato / responsável</th><th>Previsão</th><th>Situação</th></tr></thead><tbody>
<?php $upcoming=query('SELECT c.*,p.nome_completo FROM comodatos c JOIN comodatarios p ON p.id=c.comodatario_id WHERE c.ativo=1 ORDER BY c.data_fim IS NULL,c.data_fim,c.id LIMIT 6')->fetchAll(); foreach($upcoming as $row): ?><tr><td><a href="app.php?module=comodatos&action=edit&id=<?= $row['id'] ?>">#<?= $row['id'] ?> · <?= e($row['nome_completo']) ?></a></td><td><?= date_br($row['data_fim']) ?></td><td><span class="badge <?= $row['data_fim'] && $row['data_fim']<date('Y-m-d')?'warning':'' ?>"><?= $row['data_fim'] && $row['data_fim']<date('Y-m-d')?'Atrasado':'Em aberto' ?></span></td></tr><?php endforeach ?>
<?php if(!$upcoming): ?><tr><td colspan="3" class="empty">Nenhuma devolução pendente.<br><small>Cadastre os comodatos existentes para acompanhar os empréstimos.</small></td></tr><?php endif ?></tbody></table></div></section>
<section class="panel overview"><div class="eyebrow">SEU PARQUE DE EQUIPAMENTOS</div><h2>Ocupação do inventário</h2><div class="ratio"><?= $total?round($used/$total*100):0 ?><small>%</small></div><progress max="<?= max(1,$total) ?>" value="<?= $used ?>"></progress><p><?= $used ?> de <?= $total ?> itens ativos estão em comodato.</p><a href="app.php?module=inventario">Explorar inventário →</a></section></div>
<section class="panel"><div class="panel-heading"><div><h2>Organize a operação</h2><p>Do cadastro do equipamento ao acompanhamento da entrega.</p></div></div><div class="quick-links"><a href="app.php?module=inventario&action=edit"><b>01 · Registrar equipamento</b><span>Cadastre cada item físico individualmente.</span></a><a href="app.php?module=comodatarios&action=edit"><b>02 · Cadastrar colaborador</b><span>Mantenha os dados essenciais do responsável.</span></a><a href="app.php?module=comodatos&action=edit"><b>03 · Vincular comodato</b><span>Relacione empresa, colaborador e itens.</span></a></div></section>
