<?php $closed=$module==='comodatos' && $id && !$record['ativo']; ?>
<a class="back-link" href="app.php?module=<?= e($module) ?>">← Voltar à lista</a>
<section class="panel form-panel"><div class="panel-heading"><div><h2><?= $id?'Registro #'.$id:'Cadastrar '.$modules[$module]['singular'] ?></h2><p><?= $closed?'Comodato encerrado em '.date_br($record['devolvido_em']).'. Histórico preservado.':'Preencha os campos abaixo. Os campos com * são obrigatórios.' ?></p></div></div>
<form method="post" id="record-form" data-module="<?= e($module) ?>"><?= csrf() ?><fieldset <?= $closed?'disabled':'' ?>><div class="form-grid">
<?php if($module==='inventario') (static function(array $record): void { require __DIR__.'/inventory-fields.php'; })($record); ?>
<?php foreach($modules[$module]['fields'] as $key=>$f): if($module==='inventario' && $key==='modelo_id') continue; $value=$record[$key]??($key==='data_inicio'?date('Y-m-d'):''); ?><div class="form-field <?= $f[1]==='textarea'?'full':'' ?>"><label for="<?= $module==='comodatos' && $f[1]==='select'?$key.'-trigger':$key ?>"><?= e($f[0]) ?><?= $f[2]?' *':'' ?></label>
<?php if($f[1]==='textarea'): ?><textarea id="<?= $key ?>" name="<?= $key ?>" rows="3" <?= $f[2]?'required':'' ?>><?= e($value) ?></textarea>
<?php elseif($f[1]==='select'): ?><?php if($module==='comodatos'):
$pickerKind=$f[3]; $pickerId=$pickerName=$key; $pickerValue=$value; $pickerTitle=$f[0];
$pickerLabel=$value?(string)query("SELECT `{$modules[$f[3]]['label']}` FROM `{$f[3]}` WHERE id=?",[(int)$value])->fetchColumn():'';
require __DIR__.'/picker.php';
else: ?><select id="<?= $key ?>" name="<?= $key ?>" required><option value="">Selecione</option><?php foreach(options($f[3],(int)$value) as $opt): ?><option value="<?= $opt['id'] ?>" <?= $value==$opt['id']?'selected':'' ?>><?= e($opt['label']) ?></option><?php endforeach ?></select><?php endif ?><small>Não encontrou? <a href="app.php?module=<?= $f[3] ?>&action=edit" target="_blank" rel="noopener">Cadastrar em outra aba ↗</a> e depois recarregue este formulário.</small>
<?php else: ?><input id="<?= $key ?>" type="<?= $f[1] ?>" name="<?= $key ?>" value="<?= $f[1]==='password'?'':e($value) ?>" <?= $f[2]?'required':'' ?> <?= isset($f[3]) && is_int($f[3])?'maxlength="'.$f[3].'"':'' ?> <?= $f[1]==='password'?'autocomplete="new-password" minlength="10"':'' ?>><?php if($key==='password'): ?><small><?= $id?'Deixe em branco para manter a senha. ':'' ?>Mínimo de 10 caracteres.</small><?php endif ?><?php endif ?></div><?php endforeach ?>
<?php if($module!=='comodatos'): $status=$module==='users'?'active':'ativo'; ?><label class="checkbox full"><input type="checkbox" name="<?= $status ?>" value="1" <?= ($error?isset($_POST[$status]):($record[$status]??1))?'checked':'' ?>>Registro ativo</label><?php endif ?>
</div>
<?php if($module==='inventario'): ?><div class="notice">Cada cadastro representa um único equipamento. Use o patrimônio para identificar o item; se não houver etiqueta, o número interno do registro será a referência.</div><?php endif ?>
<?php if($module==='comodatos'):
$selected=$error?array_map('intval',(array)($_POST['itens']??[])):array_map('intval',query('SELECT inventario_id FROM comodato_itens WHERE comodato_id=?'.($closed?'':' AND ativo=1'),[$id])->fetchAll(PDO::FETCH_COLUMN));
$labels=array_column(equipment_labels($selected),'label','id');
$reservationToken=$closed?'':reservation_context($id,(string)($_POST['reserva_token']??''));
?><div class="item-picker" data-loan-id="<?= $id ?>" data-closed="<?= (int)$closed ?>"><h3>Equipamentos do comodato *</h3><p>Escolha um equipamento por linha. Os itens selecionados ficam reservados enquanto você preenche o formulário.</p><input type="hidden" name="reserva_token" value="<?= e($reservationToken) ?>"><p id="reservation-status" class="field-status" role="status" aria-live="polite"></p><div class="equipment-rows"><?php foreach($selected?:[0] as $index=>$itemId): ?><div class="equipment-row"><label for="equipment-<?= $index ?>-trigger">Equipamento <?= $index+1 ?> *</label><div class="equipment-controls"><?php $pickerKind='inventario'; $pickerId='equipment-'.$index; $pickerName='itens[]'; $pickerValue=$itemId?:''; $pickerLabel=$labels[$itemId]??''; $pickerTitle='equipamentos'; require __DIR__.'/picker.php'; ?><?php if(!$closed): ?><button class="remove-equipment" type="button" aria-label="Remover equipamento <?= $index+1 ?>">Remover</button><?php endif ?></div></div><?php endforeach ?></div><?php if(!$closed): ?><button type="button" class="add-equipment"><span>Adicionar +</span></button><template id="equipment-row-template"><div class="equipment-row"><label>Equipamento *</label><div class="equipment-controls"><?php $pickerKind='inventario'; $pickerId='equipment-new'; $pickerName='itens[]'; $pickerValue=$pickerLabel=''; $pickerTitle='equipamentos'; require __DIR__.'/picker.php'; ?><button class="remove-equipment" type="button" aria-label="Remover equipamento">Remover</button></div></div></template><noscript><p class="notice error">Ative o JavaScript para buscar e reservar os equipamentos deste comodato.</p></noscript><?php endif ?></div><?php endif ?>
<?php if(!$closed): ?><div class="form-actions"><button class="button">Salvar registro</button><a class="button secondary" href="app.php?module=<?= e($module) ?>">Cancelar</a></div><?php endif ?></fieldset></form>
<?php if($module==='comodatos' && $id && !$closed): ?><form class="close-form" method="post" data-confirm="Confirmar a devolução de todos os itens e encerrar este comodato?"><?= csrf() ?><input type="hidden" name="operation" value="close"><div><h3>Recebeu todos os equipamentos?</h3><p>A devolução encerra o comodato e libera seus itens para novos empréstimos.</p></div><button class="button secondary">Registrar devolução</button></form><?php endif ?>
</section>
<?php if($module==='inventario' && $id): $history=query('SELECT c.id,c.data_inicio,c.devolvido_em,ci.ativo,p.nome_completo FROM comodato_itens ci JOIN comodatos c ON c.id=ci.comodato_id JOIN comodatarios p ON p.id=c.comodatario_id WHERE ci.inventario_id=? ORDER BY c.id DESC',[$id])->fetchAll(); ?><section class="panel"><div class="panel-heading"><h2>Histórico do equipamento</h2></div><div class="table-wrap"><table><thead><tr><th>Comodato</th><th>Responsável</th><th>Início</th><th>Situação do vínculo</th></tr></thead><tbody><?php foreach($history as $h): ?><tr><td><a href="app.php?module=comodatos&action=edit&id=<?= $h['id'] ?>">#<?= $h['id'] ?></a></td><td><?= e($h['nome_completo']) ?></td><td><?= date_br($h['data_inicio']) ?></td><td><?= $h['ativo']?'Em uso':'Finalizado' ?></td></tr><?php endforeach ?><?php if(!$history): ?><tr><td colspan="4" class="empty">Este equipamento ainda não tem empréstimos registrados.</td></tr><?php endif ?></tbody></table></div></section><?php endif ?>
