<?php $closed=$module==='comodatos' && $id && !$record['ativo']; ?>
<a class="back-link" href="app.php?module=<?= e($module) ?>">← Voltar à lista</a>
<section class="panel form-panel"><div class="panel-heading"><div><h2><?= $id?'Registro #'.$id:'Cadastrar '.$modules[$module]['singular'] ?></h2><p><?= $closed?'Comodato encerrado em '.date_br($record['devolvido_em']).'. Histórico preservado.':'Preencha os campos abaixo. Os campos com * são obrigatórios.' ?></p></div></div>
<form method="post"><?= csrf() ?><fieldset <?= $closed?'disabled':'' ?>><div class="form-grid">
<?php foreach($modules[$module]['fields'] as $key=>$f): $value=$record[$key]??($key==='data_inicio'?date('Y-m-d'):''); ?><label class="<?= $f[1]==='textarea'?'full':'' ?>" for="<?= $key ?>"><?= e($f[0]) ?><?= $f[2]?' *':'' ?>
<?php if($f[1]==='textarea'): ?><textarea id="<?= $key ?>" name="<?= $key ?>" rows="3" <?= $f[2]?'required':'' ?>><?= e($value) ?></textarea>
<?php elseif($f[1]==='select'): ?><select id="<?= $key ?>" name="<?= $key ?>" required><option value="">Selecione</option><?php foreach(options($f[3],(int)$value) as $opt): ?><option value="<?= $opt['id'] ?>" <?= $value==$opt['id']?'selected':'' ?>><?= e($opt['label']) ?></option><?php endforeach ?></select><small>Não encontrou? <a href="app.php?module=<?= $f[3] ?>&action=edit" target="_blank" rel="noopener">Cadastrar em outra aba ↗</a> e depois recarregue este formulário.</small>
<?php else: ?><input id="<?= $key ?>" type="<?= $f[1] ?>" name="<?= $key ?>" value="<?= $f[1]==='password'?'':e($value) ?>" <?= $f[2]?'required':'' ?> <?= isset($f[3]) && is_int($f[3])?'maxlength="'.$f[3].'"':'' ?> <?= $f[1]==='password'?'autocomplete="new-password" minlength="10"':'' ?>><?php if($key==='password'): ?><small><?= $id?'Deixe em branco para manter a senha. ':'' ?>Mínimo de 10 caracteres.</small><?php endif ?><?php endif ?></label><?php endforeach ?>
<?php if($module!=='comodatos'): $status=$module==='users'?'active':'ativo'; ?><label class="checkbox full"><input type="checkbox" name="<?= $status ?>" value="1" <?= ($error?isset($_POST[$status]):($record[$status]??1))?'checked':'' ?>>Registro ativo</label><?php endif ?>
</div>
<?php if($module==='inventario'): ?><div class="notice">Cada cadastro representa um único equipamento. Use o patrimônio para identificar o item; se não houver etiqueta, o número interno do registro será a referência.</div><?php endif ?>
<?php if($module==='comodatos'):
$selected=$error?array_map('intval',(array)($_POST['itens']??[])):array_map('intval',query('SELECT inventario_id FROM comodato_itens WHERE comodato_id=?'.($closed?'':' AND ativo=1'),[$id])->fetchAll(PDO::FETCH_COLUMN));
$available=query('SELECT i.id,i.patrimonio,CONCAT(ma.nome," · ",m.nome) modelo FROM inventario i JOIN modelos m ON m.id=i.modelo_id JOIN marcas ma ON ma.id=m.marca_id WHERE (i.ativo=1 AND NOT EXISTS (SELECT 1 FROM comodato_itens ci WHERE ci.inventario_id=i.id AND ci.ativo=1 AND ci.comodato_id<>?)) OR EXISTS (SELECT 1 FROM comodato_itens ci WHERE ci.inventario_id=i.id AND ci.comodato_id=? AND (ci.ativo=1 OR ?=1)) ORDER BY ma.nome,m.nome,i.id',[$id,$id,(int)$closed])->fetchAll();
?><div class="item-picker"><h3>Equipamentos do comodato *</h3><p>Selecione os itens físicos entregues. Itens em outros comodatos abertos não ficam disponíveis.</p><input type="search" id="item-search" placeholder="Filtrar equipamentos por modelo ou patrimônio" aria-label="Filtrar equipamentos"><div class="item-options"><?php foreach($available as $item): if($closed && !in_array((int)$item['id'],$selected))continue; ?><label class="item-option"><input type="checkbox" name="itens[]" value="<?= $item['id'] ?>" <?= in_array((int)$item['id'],$selected)?'checked':'' ?>><span><b><?= e($item['modelo']) ?></b><small>Item #<?= $item['id'] ?> · Patrimônio: <?= e($item['patrimonio']?:'não informado') ?></small></span></label><?php endforeach ?><?php if(!$available): ?><p class="empty">Nenhum equipamento disponível. <a href="app.php?module=inventario&action=edit">Cadastre um item no inventário.</a></p><?php endif ?></div></div><?php endif ?>
<?php if(!$closed): ?><div class="form-actions"><button class="button">Salvar registro</button><a class="button secondary" href="app.php?module=<?= e($module) ?>">Cancelar</a></div><?php endif ?></fieldset></form>
<?php if($module==='comodatos' && $id && !$closed): ?><form class="close-form" method="post" data-confirm="Confirmar a devolução de todos os itens e encerrar este comodato?"><?= csrf() ?><input type="hidden" name="operation" value="close"><div><h3>Recebeu todos os equipamentos?</h3><p>A devolução encerra o comodato e libera seus itens para novos empréstimos.</p></div><button class="button secondary">Registrar devolução</button></form><?php endif ?>
</section>
<?php if($module==='inventario' && $id): $history=query('SELECT c.id,c.data_inicio,c.devolvido_em,ci.ativo,p.nome_completo FROM comodato_itens ci JOIN comodatos c ON c.id=ci.comodato_id JOIN comodatarios p ON p.id=c.comodatario_id WHERE ci.inventario_id=? ORDER BY c.id DESC',[$id])->fetchAll(); ?><section class="panel"><div class="panel-heading"><h2>Histórico do equipamento</h2></div><div class="table-wrap"><table><thead><tr><th>Comodato</th><th>Responsável</th><th>Início</th><th>Situação do vínculo</th></tr></thead><tbody><?php foreach($history as $h): ?><tr><td><a href="app.php?module=comodatos&action=edit&id=<?= $h['id'] ?>">#<?= $h['id'] ?></a></td><td><?= e($h['nome_completo']) ?></td><td><?= date_br($h['data_inicio']) ?></td><td><?= $h['ativo']?'Em uso':'Finalizado' ?></td></tr><?php endforeach ?><?php if(!$history): ?><tr><td colspan="4" class="empty">Este equipamento ainda não tem empréstimos registrados.</td></tr><?php endif ?></tbody></table></div></section><?php endif ?>
