<?php
$assetVersions=[];
foreach(['app.css','pickers.css','app.js'] as $asset) $assetVersions[$asset]=substr(hash_file('sha256',__DIR__.'/../assets/'.$asset),0,12);
?>
<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($title) ?> · GDC</title><link rel="stylesheet" href="assets/app.css?v=<?= $assetVersions['app.css'] ?>"><link rel="stylesheet" href="assets/pickers.css?v=<?= $assetVersions['pickers.css'] ?>"></head>
<body><aside class="sidebar"><a class="brand" href="app.php"><span class="brand-icon">G</span><span>GDC<small>Gestão de comodatos</small></span></a><div class="nav-label">ESPAÇO DE TRABALHO</div><nav aria-label="Principal"><a class="<?= $module==='dashboard'?'selected':'' ?>" href="app.php">Visão geral</a><?php foreach(['comodatos','inventario','comodatarios','comodantes','marcas','modelos','tipos_equipamentos','users'] as $key): ?><a class="<?= $module===$key?'selected':'' ?>" href="app.php?module=<?= $key ?>"><?= e($modules[$key]['title']) ?></a><?php endforeach ?></nav><div class="sidebar-footer">Seu inventário.<br>Todo o controle em um lugar.</div></aside>
<div class="workspace"><header class="topbar"><span>Patrimônio & operações <span class="muted">/ <?= e($title) ?></span></span><div class="account"><span><?= e($me['name']) ?></span><form method="post" action="logout.php"><?= csrf() ?><button class="text-button">Sair</button></form></div></header><main><div class="page-heading"><div><div class="eyebrow">GESTÃO DE EQUIPAMENTOS</div><h1><?= e($title) ?></h1><p><?= e($module==='dashboard'?'Acompanhe seu inventário e os equipamentos com seus colaboradores.':$modules[$module]['description']) ?></p></div><a class="button" href="app.php?module=<?= $module==='dashboard'?'comodatos':e($module) ?>&action=edit">+ <?= $module==='dashboard'?'Novo comodato':'Cadastrar' ?></a></div>
<?php if(isset($_SESSION['flash'])): ?><div class="notice success" role="status"><?= e($_SESSION['flash']) ?></div><?php unset($_SESSION['flash']); endif ?>
<?php if($error): ?><div class="notice error" role="alert"><?= e($error) ?></div><?php endif ?>
<?php require __DIR__.'/'.($module==='dashboard'?'dashboard':($action==='edit'?'form':'list')).'.php'; ?>
<footer class="footer">GDC · Gestão de comodatos e inventário <span><?= date('d/m/Y') ?></span></footer></main></div><script src="assets/app.js?v=<?= $assetVersions['app.js'] ?>" defer></script></body></html>
