<?php
$search=trim((string)($_GET['q']??'')); $status=(string)($_GET['status']??'');
[$rows,$count,$page,$pages]=listing($module,$search,$status,(int)($_GET['page']??1));
$columns=match($module) {
 'comodatos'=>['id'=>'Nº','comodante'=>'Comodante','comodatario'=>'Comodatário','data_inicio'=>'Início','data_fim'=>'Previsão','devolvido_em'=>'Devolução'],
 'inventario'=>['id'=>'Item','patrimonio'=>'Patrimônio','modelo'=>'Modelo','responsavel'=>'Responsável'],
 'modelos'=>['nome'=>'Modelo','marca'=>'Marca','tipo'=>'Tipo'],
 'users'=>['name'=>'Nome','email'=>'E-mail'],
 'comodantes'=>['nome_fantasia'=>'Nome fantasia','razao_social'=>'Razão social','cnpj'=>'CNPJ'],
 'comodatarios'=>['nome_completo'=>'Nome completo','cpf'=>'CPF'],
 'marcas'=>['nome'=>'Marca','identificador_externo'=>'Identificador externo'],
 default=>['nome'=>'Nome','descricao'=>'Descrição']
};
?>
<section class="panel"><form class="filters" method="get"><input type="hidden" name="module" value="<?= e($module) ?>"><label>Buscar<input type="search" name="q" value="<?= e($search) ?>" placeholder="Pesquisar nesta lista"></label><label>Situação<select name="status"><?php $filters=[''=>'Todas','1'=>$module==='comodatos'?'Em aberto':'Ativos','0'=>$module==='comodatos'?'Encerrados':'Inativos']; if($module==='comodatos')$filters['overdue']='Atrasados'; if($module==='inventario')$filters+=['available'=>'Disponíveis','loaned'=>'Em comodato']; foreach($filters as $v=>$label): ?><option value="<?= $v ?>" <?= $status===(string)$v?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><button class="button secondary">Filtrar</button><a href="app.php?module=<?= e($module) ?>">Limpar</a></form><div class="table-meta"><?= $count ?> registro(s)</div><div class="table-wrap"><table><thead><tr><?php foreach($columns as $label): ?><th><?= $label ?></th><?php endforeach ?><th>Situação</th><th>Ações</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><?php foreach($columns as $key=>$label): ?><td><?= in_array($key,['data_inicio','data_fim','devolvido_em']) ? ($row[$key]?date_br($row[$key]):'—') : e($row[$key]??'—') ?></td><?php endforeach ?><td><?php $active=$row[$module==='users'?'active':'ativo']; $state=$active?'Ativo':'Inativo'; if($module==='comodatos') $state=!$active?'Encerrado':($row['data_fim'] && $row['data_fim']<date('Y-m-d')?'Atrasado':'Em aberto'); if($module==='inventario' && $active)$state=$row['comodato_id']?'Em comodato':'Disponível'; ?><span class="badge <?= !$active?'neutral':($state==='Atrasado'?'warning':'') ?>"><?= $state ?></span></td><td><a class="row-action" href="app.php?module=<?= e($module) ?>&action=edit&id=<?= $row['id'] ?>">Abrir →</a></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td class="empty" colspan="<?= count($columns)+2 ?>">Nenhum registro encontrado.<br><small>Altere os filtros ou use “Cadastrar” para começar.</small></td></tr><?php endif ?></tbody></table></div><nav class="pagination" aria-label="Paginação"><span>Página <?= $page ?> de <?= $pages ?></span><?php foreach(['Anterior'=>$page-1,'Próxima'=>$page+1] as $label=>$target): if($target>=1 && $target<=$pages): ?><a class="button secondary" href="?<?= e(http_build_query(['module'=>$module,'q'=>$search,'status'=>$status,'page'=>$target])) ?>"><?= $label ?></a><?php endif; endforeach ?></nav></section>
